language: python
sudo: required
services: docker

addons:
  apt:
    sources:
    - sourceline: 'ppa:ubuntu-toolchain-r/test'
    - sourceline: 'ppa:inkscape.dev/stable'
    packages:
    - g++-4.9
    - mahimahi
    - mahimahi-traces
    - inkscape
    - texlive

install:
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 99

script:
  - ./test/run.py -f 2 -t 10

env:
    matrix:
        - CC_SCHEME='default_tcp'
        - CC_SCHEME='vegas'
        - CC_SCHEME='koho_cc'
        - CC_SCHEME='ledbat'
        - CC_SCHEME='pcc'
        - CC_SCHEME='verus'
        - CC_SCHEME='scream'
        - CC_SCHEME='webrtc'
        - CC_SCHEME='sprout'
        - CC_SCHEME='quic'

notifications:
  slack: keithw:WjjCMz8yip3iQrHKBmkFGI1u
  email: false
