language: python
sudo: required
services: docker

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9
  artifacts:
    paths:
    - test/pantheon-report.pdf
    target_paths: ""
    debug: true

install:
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 99
  - ./install_deps.sh

script:
  - ./autogen.sh
  - ./configure
  - make -j
  - ./run.sh

notifications:
  slack: keithw:WjjCMz8yip3iQrHKBmkFGI1u
  email: false
