language: python
sudo: required
services: docker

addons:
  apt:
    sources:
    - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
    - g++-4.9

install:
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 99

env:
    matrix:
        - CMD='EXTRA_MAHIMAHI_SHELLS="mm-onoff uplink 5 .1 mm-onoff downlink 5 .1 mm-loss uplink .1 mm-loss downlink .1"; travis_extras/travis_test.sh'
        - CMD='EXTRA_MAHIMAHI_SHELLS="mm-loss uplink .3 mm-loss downlink .3"; RUN_PY_EXTRAS="--sender-side local"; travis_extras/travis_test.sh'
        - CMD='EXTRA_MAHIMAHI_SHELLS="mm-loss uplink .2 mm-loss downlink .2"; travis_extras/travis_test.sh'
        - CMD='EXTRA_MAHIMAHI_SHELLS="mm-onoff uplink 1 1 mm-onoff downlink 1 1"; RUN_PY_EXTRAS="--sender-side local"; travis_extras/travis_test.sh'
        - CMD='EXTRA_MAHIMAHI_SHELLS="mm-onoff uplink 2 2 mm-onoff downlink 2 2"; travis_extras/travis_test.sh'
        # Run setup twice in a row to check for basic idempotency problems
        - CMD='test/pre_setup.py && test/setup.py quic        && test/setup.py quic        && test/test.py -f 2 -t 10 quic'
        - CMD='test/pre_setup.py && test/setup.py webrtc      && test/setup.py webrtc      && test/test.py -f 2 -t 10 webrtc'
        - CMD='test/pre_setup.py && test/setup.py default_tcp && test/setup.py default_tcp && test/test.py -f 2 -t 10 default_tcp'
        - CMD='test/pre_setup.py && test/setup.py vegas       && test/setup.py vegas       && test/test.py -f 2 -t 10 vegas'
        - CMD='test/pre_setup.py && test/setup.py koho_cc     && test/setup.py koho_cc     && test/test.py -f 2 -t 10 koho_cc'
        - CMD='test/pre_setup.py && test/setup.py ledbat      && test/setup.py ledbat      && test/test.py -f 2 -t 10 ledbat'
        - CMD='test/pre_setup.py && test/setup.py pcc         && test/setup.py pcc         && test/test.py -f 2 -t 10 pcc'
        - CMD='test/pre_setup.py && test/setup.py verus       && test/setup.py verus       && test/test.py -f 2 -t 10 verus'
        - CMD='test/pre_setup.py && test/setup.py scream      && test/setup.py scream      && test/test.py -f 2 -t 10 scream'
        - CMD='test/pre_setup.py && test/setup.py sprout      && test/setup.py sprout      && test/test.py -f 2 -t 10 sprout'
        - CMD='test/pre_setup.py && test/setup.py taova       && test/setup.py taova       && test/test.py -f 2 -t 10 taova'
        - CMD='test/pre_setup.py && test/setup.py copa        && test/setup.py copa        && test/test.py -f 2 -t 10 copa'
        - CMD='test/pre_setup.py && test/setup.py saturator   && test/setup.py saturator   && test/test.py -f 2 -t 10 saturator'
        - CMD='test/pre_setup.py && test/setup.py greg_saturator && test/setup.py greg_saturator && test/test.py -f 2 -t 10 greg_saturator'

script:
  - eval $CMD

notifications:
  slack: keithw:WjjCMz8yip3iQrHKBmkFGI1u
  email: false
