language: python
sudo: required
services: docker

addons:
  apt:
    sources:
    - sourceline: 'ppa:ubuntu-toolchain-r/test'
    - sourceline: 'ppa:keithw/mahimahi'
    - sourceline: 'ppa:inkscape.dev/stable'
    packages:
    - g++-4.9
    - mahimahi
    - mahimahi-traces
    - inkscape
    - texlive
    - latex-xcolor
    - protobuf-compiler
    - libprotobuf-dev
    - autotools-dev
    - dh-autoreconf
    - iptables
    - pkg-config
    - dnsmasq-base
    - apache2-dev
    - debhelper
    - libssl-dev
    - ssl-cert
    - libxcb-present-dev
    - libcairo2-dev
    - libpango1.0-dev
  artifacts:
    paths:
    - test/pantheon-report.pdf
    - test/pantheon-packet-logs.xz
    debug: true

install:
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 99

script:
  - git clone -b mm-tunnelshell https://github.com/francisyyan/mahimahi.git
  - cd mahimahi
  - ./autogen.sh
  - ./configure
  - make -j
  - sudo make install
  - cd ../test
  - ./run.py -f 2 -t 10

after_script:
  - tar caf test/pantheon-packet-logs.xz test/*.log

notifications:
  slack: keithw:WjjCMz8yip3iQrHKBmkFGI1u
  email: false
