language: python
sudo: required
services: docker

addons:
  apt:
    sources:
    - sourceline: 'ppa:ubuntu-toolchain-r/test'
    - sourceline: 'ppa:keithw/mahimahi'
    - sourceline: 'ppa:inkscape.dev/stable'
    packages:
    - g++-4.9
    - mahimahi
    - mahimahi-traces
    - inkscape
    - texlive
  artifacts:
    paths:
    - test/pantheon-report.pdf
    debug: true

install:
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 99

script:
  - ./run.sh

notifications:
  slack: keithw:WjjCMz8yip3iQrHKBmkFGI1u
  email: false
