language: python
sudo: required
services: docker

branches:
  only:
    - refactor

addons:
  apt:
    sources:
    - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
    - g++-4.9

install:
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 99
  - pip install matplotlib numpy tabulate pyyaml colorama

env:
    matrix:
      - CMD='./test/setup.py --schemes quic --install-deps &&
        ./test/setup.py --schemes quic --setup &&
        ./test/test.py local --schemes quic -t 10'
      - CMD='SCHEMES="default_tcp vegas ledbat pcc verus sprout webrtc
        scream copa taova koho_cc calibrated_koho saturator" &&
        ./test/setup.py --schemes "$SCHEMES" --install-deps &&
        ./test/setup.py --schemes "$SCHEMES" --setup &&
        ./test/test.py local --schemes "$SCHEMES" -t 10'

script:
  - ./install_deps.py && eval $CMD

notifications:
    email: false
