schemes:
  default_tcp:
    friendly_name: Cubic
    color: black
    marker: 'o'
  vegas:
    friendly_name: Vegas
    color: olive
    marker: 'h'
  bbr:
    friendly_name: BBR
    color: mediumblue
    marker: 'H'
    qdisc: 'fq'
  ledbat:
    friendly_name: LEDBAT
    color: darkgreen
    marker: 'D'
  pcc:
    friendly_name: PCC
    color: maroon
    marker: '>'
  verus:
    friendly_name: Verus
    color: brown
    marker: '^'
  sprout:
    friendly_name: Sprout
    color: dodgerblue
    marker: 'v'
  quic:
    friendly_name: QUIC
    color: orangered
    marker: '8'
  scream:
    friendly_name: SCReAM
    color: seagreen
    marker: 'p'
  webrtc:
    friendly_name: WebRTC
    color: darkgoldenrod
    marker: 'P'
  copa:
    friendly_name: Copa
    color: chocolate
    marker: 's'
  taova:
    friendly_name: Tao
    color: darkcyan
    marker: '<'
  koho_cc:
    friendly_name: KohoCC
    color: gray
    marker: '+'
  calibrated_koho:
    friendly_name: CalibratedKoho
    color: silver
    marker: 'x'
  indigo:
    friendly_name: Indigo
    color: indigo
    marker: '*'
  indigo_cellular:
    friendly_name: Indigo-cellular
    color: violet
    marker: 'd'
  indigo_no_calibration:
    friendly_name: Indigo w/o calib
    color: blueviolet
    marker: 'd'
  indigo_1_32:
    friendly_name: Indigo
    color: indigo
    marker: '*'
  indigo_1_32_no_calib:
    friendly_name: Indigo w/o calib
    color: blueviolet
    marker: 'd'
  indigo_no_queuing_delay:
    friendly_name: Indigo w/o delay
    color: mediumpurple
    marker: '^'
  indigo_no_delivery_rate:
    friendly_name: Indigo w/o deliver
    color: darkviolet
    marker: 'v'
  indigo_no_send_rate:
    friendly_name: Indigo w/o send
    color: rebeccapurple
    marker: '<'
  indigo_no_cwnd:
    friendly_name: Indigo w/o cwnd
    color: darkorchid
    marker: '>'
  fillp:
    friendly_name: FillP
    color: violet
    marker: '+'
  vivace_latency:
    friendly_name: Vivace-latency
    color: '#0149D0'
    marker: '<'
  vivace_loss:
    friendly_name: Vivace-loss
    color: '#003CAD'
    marker: '>'
  vivace_lte:
    friendly_name: Vivace-LTE
    color: '#002A79'
    marker: '^'

kernel_attrs:
  default_qdisc: pfifo_fast
  sock_recv_bufs:
    remote:
      max: '33554432'
      default: '16777216'
    local:
      max: '33554432'
      default: '16777216'
