schemes:
  default_tcp:
    friendly_name: TCP Cubic
    color: black
    marker: 'd'
  vegas:
    friendly_name: TCP Vegas
    color: silver
    marker: 'h'
  bbr:
    friendly_name: TCP BBR
    color: gold
    marker: '^'
    qdisc: 'fq'
  ledbat:
    friendly_name: LEDBAT
    color: green
    marker: '<'
  pcc:
    friendly_name: PCC
    color: cyan
    marker: '>'
  verus:
    friendly_name: Verus
    color: skyblue
    marker: 'H'
  sprout:
    friendly_name: Sprout
    color: orange
    marker: 'p'
  quic:
    friendly_name: QUIC Cubic
    color: magenta
    marker: '8'
  scream:
    friendly_name: SCReAM
    color: pink
    marker: '1'
  webrtc:
    friendly_name: WebRTC media
    color: brown
    marker: 'v'
  copa:
    friendly_name: Copa
    color: red
    marker: 'o'
  taova:
    friendly_name: TaoVA-100x
    color: gray
    marker: '*'
  koho_cc:
    friendly_name: KohoCC
    color: blue
    marker: '+'
  calibrated_koho:
    friendly_name: CalibratedKoho
    color: olive
    marker: 'D'
  indigo:
    friendly_name: Indigo
    color: indigo
    marker: 's'
  indigo-2-layer-128-dim:
    friendly_name: Indigo-2-layer-128-dim
    color: black 
    marker: 'o'
  indigo-2-layer-64-dim:
    friendly_name: Indigo-2-layer-64-dim
    color: green 
    marker: 'v'
  indigo-2-layer-32-dim:
    friendly_name: Indigo-2-layer-32-dim
    color: blue 
    marker: '^'
  indigo-2-layer-16-dim:
    friendly_name: Indigo-2-layer-16-dim
    color: red 
    marker: '<'
  indigo-2-layer-8-dim:
    friendly_name: Indigo-2-layer-8-dim
    color: gray
    marker: '>'
  indigo-2-layer-4-dim:
    friendly_name: Indigo-2-layer-4-dim
    color: olive
    marker: '1'
  indigo-1-layer-256-dim:
    friendly_name: Indigo-1-layer-256-dim
    color: magenta
    marker: '2'
  indigo-1-layer-128-dim:
    friendly_name: Indigo-1-layer-128-dim
    color: orange 
    marker: '3'
  indigo-1-layer-64-dim:
    friendly_name: Indigo-1-layer-64-dim
    color: brown 
    marker: '4'
  indigo-1-layer-32-dim:
    friendly_name: Indigo-1-layer-32-dim
    color: gold 
    marker: '8'
  indigo-1-layer-16-dim:
    friendly_name: Indigo-1-layer-16-dim
    color: cyan
    marker: 'p'
  indigo-1-layer-8-dim:
    friendly_name: Indigo-1-layer-8-dim
    color: skyblue
    marker: 'P'
  indigo-1-layer-4-dim:
    friendly_name: Indigo-1-layer-4-dim
    color: silver
    marker: '*'

kernel_attrs:
  default_qdisc: pfifo_fast
  sock_recv_bufs:
    remote:
      max: '33554432'
      default: '16777216'
    local:
      max: '33554432'
      default: '16777216'
